seed: 42
device: cuda

net_g:
  type: ImageGenerator
  params:
    nz: 64
    channels: [256, 256, 256, 256]
    cardinalities: [32, 32, 32, 32]
    n_blocks: [2, 2, 2, 2]
    expansion_f: 2

net_d:
  type: SymmetricDiscriminator
  params:
    channels: [256, 256, 256, 256]
    cardinalities: [32, 32, 32, 32]
    n_blocks: [2, 2, 2, 2]
    expansion_f: 2
    use_spectral_norm: false

data:
  type: CelebA32
  params:
    imsize: 32
    train_aug: true
  loader:
    batch_size: 512

optim_g:
  type: Adam
  params:
    lr: 0.0002
    betas: [0., 0.9]

optim_d:
  type: Adam
  params:
    lr: 0.0002
    betas: [0., 0.9]

lossf: rpgan
use_gp: false
use_r1_gp: true
use_r2_gp: true
zero_centered_gp_gamma: 5
mind_the_gap: false
skip_confident_model: false

num_iters: 40000
log_every: 10
img_every: 100
fid_every: 1000
save_every: 10000
resume_from: ~
